arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
                                                                        #kdl_kinematics_plugin/KDLKinematicsPlugin
                                                                        #srv_kinematics_plugin/SrvKinematicsPlugin
                                                                        #trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  solve_type: Distance
