sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/rtt_lwr.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ADDITIONAL_DEBS="curl"
    
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic" ADDITIONAL_DEBS="curl libgazebo7-dev"
    - ROS_DISTRO="melodic"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
