# Adapted from https://github.com/jbohren/conman
language:
  - cpp
  - python
  - ruby
  - lua
python:
  - "2.7"

sudo: required

compiler:
  - gcc
before_install:
  # Define some config vars
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export EXTRA_CMAKE_ARGS="-DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB"
  # Bootstrap a minimal ROS installation
  - git clone https://github.com/jhu-lcsr/ros_ci_tools /tmp/ros_ci_tools && export PATH=/tmp/ros_ci_tools:$PATH
  - ros_ci_bootstrap public
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Create non-isolated workspace
  - mkdir -p ~/ws/src
  - pushd ~/ws/src
  - ln -s $CI_SOURCE_PATH
  - git clone https://github.com/jhu-lcsr-forks/rtt_ros_integration.git
  - pushd rtt_ros_integration
  - find . -maxdepth 1 -type d -exec touch {}/CATKIN_IGNORE \;
  - rm CATKIN_IGNORE
  - rm rtt_actionlib/CATKIN_IGNORE
  - popd
  - git clone https://github.com/jbohren/rqt_dot.git
  - git clone https://github.com/jhu-lcsr/rtt_ros_control.git
  - git clone https://github.com/jhu-lcsr/rtt_gazebo
  - git clone https://github.com/kuka-isir/rtt_ros_kdl_tools
  - popd
  - wget https://raw.githubusercontent.com/IDSCETHZurich/re_trajectory-generator/master/kuka_IK/include/friComm.h
  - mv friComm.h ~/ws/src/rtt_lwr/lwr_hardware/kuka_lwr_fri/include/kuka_lwr_fri/friComm.h
  - rosdep install -r --from-paths ~/ws/src --ignore-src --rosdistro $ROS_DISTRO -y
  # Currently waiting for this rosdep rule to be merged
  - sudo apt-get install -qq google-mock lcov
  - sudo pip install cpp-coveralls --use-mirrors

install:
  # build the normal catkin workspace
  - pushd ~/ws
  - catkin_make -j2 --cmake-args -DCMAKE_BUILD_TYPE=Debug 
    # -DENABLE_COVERAGE=On 

script:
  # Run tests
  - source devel/setup.bash
  - catkin_make 
